{
  imports = [
    ./avahi.nix
    ./bluetooth.nix
    ./bootloader.nix
    ./gnome.nix
    ./hyprland.nix
    ./libinput.nix
    ./locale.nix
    ./location.nix
    ./network.nix
    ./nix.nix
    ./nixpkgs.nix
    ./pipewire.nix
    ./plymouth.nix
    ./users.nix
    ./wayland.nix
    ./weylus.nix
    ./xdg.nix
    ./xserver.nix
  ];
}
