{
  imports = [
    ./boot
    ./network
    ./services/avahi.nix
    ./services/endlessh.nix
    ./services/fail2ban.nix
    ./services/iperf.nix
    ./services/libinput.nix
    ./services/openssh.nix
    ./services/preload.nix
    ./home-manager.nix
    ./locale.nix
    ./location.nix
    ./nix.nix
    ./nixpkgs.nix
    ./security.nix
    ./user.nix
  ];
}
