{
  imports = [
    ./services/avahi.nix
    ./services/endlessh.nix
    ./services/fail2ban.nix
    ./services/libinput.nix
    ./services/openssh.nix
    ./services/preload.nix
    ./boot.nix
    ./home-manager.nix
    ./locale.nix
    ./location.nix
    ./network.nix
    ./nix.nix
    ./nixpkgs.nix
    ./plymouth.nix
    ./security.nix
    ./systemd.nix
    ./users.nix
  ];
}
